base_url = 'https://qa-scooter.praktikum-services.ru/'

name = 'Татьяна'
surname = 'Трачук'
address = 'Лермонтова, 89'
subway = 'Бульвар Рокоссовского'
phone = '895687894567'
email = 'tatina@874.ru'
password = '12345'
scooter_color = 'чёрный жемчуг'
comment_for_the_courier = 'оставить у двери'


name_test2 = 'Смирнов'
surname_test2 = 'Иван'
address_test2 = 'Крылова, 145'
subway_test2 = 'Бульвар Рокоссовского'
phone_test2 = '89567845609'
email_test2 = 'ivan@909.ru'
password_test2 = '00000'
scooter_color_test2 = 'серая безысходность'
comment_for_the_courier_test2 = 'не звонить в дверь'